### ISSUE TITLE
Not able to run this service on mobile device

### ISSUE THREAD

**Issue by vandna06** [Jnegrier/wdio-novus-visual-regression-service#16]
While running the wdio script on mobile device, getting below error
browser.checkDocument is not a function.

Also, i tried using browser.checkViewport() and browser.checkElement(), but still getting same error.

Request you to check.

**Comment by Jnegrier** [comment]
Hi @vandna06 thanks for letting me know about this

Could you give me more info about your config please and also if you are using Typescript?

I don't have any setup for mobile devices, so any info about how to replicate your config is welcome 👍

**Comment by vandna06** [comment]
Hi @Jnegrier , Thanks for the support.

The issue is resolved now. seems like some issue with the node modules when i reinstall node modules , it worked fine.

Thanks.

**Comment by Jnegrier** [comment]
Happy to help! have a good day @vandna06
